[package]
name = "runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28.0", features = ["full"] }
rand = "0.8.5"
toml = "0.8.19"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
onnxruntime = "0.0.14"
ndarray = "0.16.1"
