[package]
name = "runtime"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
name = "runtime"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
async-trait = "0.1.83"
ndarray = "0.16.1"
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.28.0", features = ["full"] }
toml = "0.8.19"
half = "2.4.1"
ctrlc = "3.2"
cursive = "0.21"
clap = { version = "4.5.19", features = ["derive"] }
serde_json = "1.0.128"
chrono = "0.4.38"

# [build-dependencies]
# pkg-config = "0.3.31"

# [target.'cfg(target_os = "macos")'.dependencies]
# onnxruntime-sys = { version = "0.0.14", features = ["disable-sys-build"] }
