[robot]
name = "microstompy"
height = 0.21            # m
weight = 5               # kg

[robot.legs.left]
hip_roll = { id = 1, pid = { p = 10.0, i = 0.0, d = 0.3 }, limits = { lower = -4.0, upper = 1.0 } }
hip_yaw = { id = 2, pid = { p = 10.0, i = 0.0, d = 0.3 }, limits = { lower = 2.64, upper = 5.64 } }
hip_pitch = { id = 3, pid = { p = 10.0, i = 0.0, d = 0.3 }, limits = { lower = -1.64, upper = 1.64 } }
knee_pitch = { id = 4, pid = { p = 10.0, i = 0.0, d = 0.3 }, limits = { lower = -2.5, upper = 0.5 } }
ankle_pitch = { id = 5, pid = { p = 10.0, i = 0.0, d = 0.3 }, limits = { lower = -0.3, upper = 0.3 } }

[robot.legs.right]
hip_roll = { id = 6, pid = { p = 10.0, i = 0.0, d = 0.3 }, limits = { lower = 2.25, upper = 4.49 } }
hip_yaw = { id = 7, pid = { p = 10.0, i = 0.0, d = 0.3 }, limits = { lower = 1.74, upper = 4.74 } }
hip_pitch = { id = 8, pid = { p = 10.0, i = 0.0, d = 0.3 }, limits = { lower = 0.05, upper = 4.05 } }
knee_pitch = { id = 9, pid = { p = 10.0, i = 0.0, d = 0.3 }, limits = { lower = -0.5, upper = 2.5 } }
ankle_pitch = { id = 10, pid = { p = 10.0, i = 0.0, d = 0.3 }, limits = { lower = -0.3, upper = 0.3 } }

[robot.arms.left]
shoulder_yaw = { id = 11, pid = { p = 10.0, i = 0.0, d = 0.3 }, limits = { lower = -1.0, upper = 2.0 } }
shoulder_pitch = { id = 12, pid = { p = 10.0, i = 0.0, d = 0.3 }, limits = { lower = 2.04, upper = 3.06 } }
elbow_pitch = { id = 13, pid = { p = 10.0, i = 0.0, d = 0.3 }, limits = { lower = -2.06, upper = -1.08 } }

[robot.arms.right]
shoulder_yaw = { id = 14, pid = { p = 10.0, i = 0.0, d = 0.3 }, limits = { lower = -1.481, upper = 1.0 } }
shoulder_pitch = { id = 15, pid = { p = 10.0, i = 0.0, d = 0.3 }, limits = { lower = 2.619, upper = 3.621 } }
elbow_pitch = { id = 16, pid = { p = 10.0, i = 0.0, d = 0.3 }, limits = { lower = -3.819, upper = 3.821 } }

[robot.parameters]
stiffness = { hip_pitch = 10.0, hip_yaw = 10.0, hip_roll = 10.0, knee_pitch = 10.0, ankle_pitch = 10.0, shoulder_pitch = 10.0, shoulder_yaw = 10.0, shoulder_roll = 10.0, elbow_pitch = 10.0, elbow_yaw = 10.0 }
damping = { hip_pitch = 0.3, hip_yaw = 0.3, hip_roll = 0.3, knee_pitch = 0.3, ankle_pitch = 0.3, shoulder_pitch = 0.3, shoulder_yaw = 0.3, shoulder_roll = 0.3, elbow_pitch = 0.3, elbow_yaw = 0.3 }
effort = { hip_pitch = 2.0, hip_yaw = 2.0, hip_roll = 2.0, knee_pitch = 2.0, ankle_pitch = 2.0, shoulder_pitch = 2.0, shoulder_yaw = 2.0, shoulder_roll = 2.0, elbow_pitch = 2.0, elbow_yaw = 2.0 }
velocity = { hip_pitch = 20.0, hip_yaw = 20.0, hip_roll = 20.0, knee_pitch = 20.0, ankle_pitch = 20.0, shoulder_pitch = 20.0, shoulder_yaw = 20.0, shoulder_roll = 20.0, elbow_pitch = 20.0, elbow_yaw = 20.0 }
friction = { hip_pitch = 0.0, hip_yaw = 0.0, hip_roll = 0.0, knee_pitch = 0.0, ankle_pitch = 0.0, elbow_pitch = 0.0, elbow_yaw = 0.0 }

[robot.default_standing_positions]
hip_roll = 0.0
hip_yaw = 0.0
hip_pitch = 0.0
knee_pitch = 0.0
ankle_pitch = 0.0
shoulder_yaw = 0.0
shoulder_pitch = 0.0
elbow_pitch = 0.0
elbow_yaw = 0.0
